// <auto-generated />
using System;
using EpycusApp.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpycusApp.Migrations
{
    [DbContext(typeof(ContextoAplicacion))]
    [Migration("20260629192011_SincronizarModelo")]
    partial class SincronizarModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EpycusApp.Models.Entidades.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.ConfiguracionPomodoro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoIniciarDescanso")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AutoIniciarEnfoque")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CiclosAntesDescansoLargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MetaDiariaCiclos")
                        .HasColumnType("int");

                    b.Property<int>("ModoPersonalizadoMin")
                        .HasColumnType("int")
                        .HasColumnName("ModoPersonalizadoMinutos");

                    b.Property<bool>("NotificacionDesktop")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SonidoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SonidoSeleccionado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TicTacActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TiempoDescansoLargoMin")
                        .HasColumnType("int");

                    b.Property<int>("TiempoDescansoMin")
                        .HasColumnType("int");

                    b.Property<int>("TiempoEstudioMin")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("VibracionActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Volumen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesPomodoro");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.DiasSemanaHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("HabitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitoId");

                    b.ToTable("DiasSemanaHabito");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.EntradaDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ActividadFisica")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DiarioTexto")
                        .HasColumnType("longtext");

                    b.Property<int>("EstadoAnimo")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("HorasSueno")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NivelEnergia")
                        .HasColumnType("int");

                    b.Property<int?>("NivelEstres")
                        .HasColumnType("int");

                    b.Property<string>("PreguntaGuia")
                        .HasColumnType("longtext");

                    b.Property<string>("RespuestaGuia")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique();

                    b.ToTable("EntradasDiario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.EstadoAnimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nota")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstadosAnimo");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.FraseMotivacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Frase")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FrasesMotivacionales");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Habito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("ConPomodoro")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RachaActual")
                        .HasColumnType("int");

                    b.Property<int>("RachaMaxima")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("RecordatorioHora")
                        .HasColumnType("time(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Habitos");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.ImagenNivelPersonaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPlaceholder")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NivelNumero")
                        .HasColumnType("int");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonajeId");

                    b.ToTable("ImagenesNivelPersonaje");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicionTipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CondicionValor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("XpRecompensa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.LogroUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LogroId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogrosUsuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.MensajeIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConversacionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("FeedbackRecibido")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("FeedbackUtil")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajesIA");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Mision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("ConPomodoro")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("FechaLimite")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCurso")
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("XpOtorgado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Misiones");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("XpRequerido")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarreraId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.PersonajeUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaSeleccionado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonajeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PersonajesUsuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.ProgresoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DiaDeGraciaUsado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaInicioRacha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimaActividad")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NivelActualId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductividadDiaria")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RachaActual")
                        .HasColumnType("int");

                    b.Property<int>("RachaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("XpTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NivelActualId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ProgresosUsuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.RecuperacionContrasena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RecuperacionesContrasena");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.RegistroHabito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HabitoId")
                        .HasColumnType("int");

                    b.Property<int>("XpOtorgado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitoId");

                    b.ToTable("RegistrosHabito");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.SesionPomodoro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiclosCompletados")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FueCompletada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("HabitoId")
                        .HasColumnType("int");

                    b.Property<int?>("MisionId")
                        .HasColumnType("int");

                    b.Property<int?>("SubTareaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("XpOtorgado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitoId");

                    b.HasIndex("MisionId");

                    b.HasIndex("SubTareaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesPomodoro");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.SubTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaCompletada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MisionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TiempoEnfoqueSegundos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.ToTable("SubTareas");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Suscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivadaPorAdminId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioSoles")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivadaPorAdminId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoCss")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EsPremium")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImagenPreviewUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.TemaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaObtenido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TemaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TemasUsuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.TipPomodoro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipsPomodoro");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.TokenRefresh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Revocado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRefresh");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptoTerminos")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("BloqueoHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("longtext");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoGoogleUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int?>("TemaActualId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("TemaActualId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.VerificacionCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VerificacionesCorreo");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.ConfiguracionPomodoro", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithOne("ConfiguracionPomodoro")
                        .HasForeignKey("EpycusApp.Models.Entidades.ConfiguracionPomodoro", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.DiasSemanaHabito", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Habito", "Habito")
                        .WithMany("DiasSemana")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.EntradaDiario", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.EstadoAnimo", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("EstadosAnimo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Habito", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Categoria", "Categoria")
                        .WithMany("Habitos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("Habitos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.ImagenNivelPersonaje", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Personaje", "Personaje")
                        .WithMany("Imagenes")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Log", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.LogroUsuario", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("LogrosUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.MensajeIA", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Mision", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Categoria", "Categoria")
                        .WithMany("Misiones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("Misiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Personaje", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.PersonajeUsuario", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Personaje", "Personaje")
                        .WithMany("PersonajesUsuario")
                        .HasForeignKey("PersonajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("PersonajesUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personaje");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.ProgresoUsuario", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Nivel", "NivelActual")
                        .WithMany("Progresos")
                        .HasForeignKey("NivelActualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithOne("Progreso")
                        .HasForeignKey("EpycusApp.Models.Entidades.ProgresoUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelActual");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.RecuperacionContrasena", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.RegistroHabito", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Habito", "Habito")
                        .WithMany("Registros")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.SesionPomodoro", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Habito", "Habito")
                        .WithMany("SesionesPomodoro")
                        .HasForeignKey("HabitoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EpycusApp.Models.Entidades.Mision", "Mision")
                        .WithMany("SesionesPomodoro")
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EpycusApp.Models.Entidades.SubTarea", "SubTarea")
                        .WithMany("SesionesPomodoro")
                        .HasForeignKey("SubTareaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("SesionesPomodoro")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habito");

                    b.Navigation("Mision");

                    b.Navigation("SubTarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.SubTarea", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Mision", "Mision")
                        .WithMany("SubTareas")
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mision");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Suscripcion", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ActivadaPorAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("Suscripciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.TemaUsuario", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Tema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("TemasUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.TokenRefresh", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany("TokensRefresh")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Usuario", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Carrera", "Carrera")
                        .WithMany("Usuarios")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EpycusApp.Models.Entidades.Tema", "TemaActual")
                        .WithMany()
                        .HasForeignKey("TemaActualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carrera");

                    b.Navigation("Rol");

                    b.Navigation("TemaActual");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.VerificacionCorreo", b =>
                {
                    b.HasOne("EpycusApp.Models.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Carrera", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Categoria", b =>
                {
                    b.Navigation("Habitos");

                    b.Navigation("Misiones");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Habito", b =>
                {
                    b.Navigation("DiasSemana");

                    b.Navigation("Registros");

                    b.Navigation("SesionesPomodoro");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Mision", b =>
                {
                    b.Navigation("SesionesPomodoro");

                    b.Navigation("SubTareas");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Nivel", b =>
                {
                    b.Navigation("Progresos");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Personaje", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("PersonajesUsuario");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.SubTarea", b =>
                {
                    b.Navigation("SesionesPomodoro");
                });

            modelBuilder.Entity("EpycusApp.Models.Entidades.Usuario", b =>
                {
                    b.Navigation("ConfiguracionPomodoro")
                        .IsRequired();

                    b.Navigation("EstadosAnimo");

                    b.Navigation("Habitos");

                    b.Navigation("LogrosUsuario");

                    b.Navigation("Misiones");

                    b.Navigation("PersonajesUsuario");

                    b.Navigation("Progreso")
                        .IsRequired();

                    b.Navigation("SesionesPomodoro");

                    b.Navigation("Suscripciones");

                    b.Navigation("TemasUsuario");

                    b.Navigation("TokensRefresh");
                });
#pragma warning restore 612, 618
        }
    }
}
