/*
 * Escalafón de Rangos Profesionales por Carrera Individual (Fases 1 a 10).
 *
 * Cada una de las 11 carreras posee 10 títulos evolutivos únicos que reflejan
 * el progreso académico y profesional real del estudiante en Epycus.
 */

export const CAREER_RANKS = {
    'Medicina': [
        'Preclínico',
        'Estudiante de Ciencias Médicas',
        'Externo de Medicina',
        'Interno de Medicina',
        'Médico Cirujano Junior',
        'Residente de Especialidad',
        'Médico Especialista',
        'Jefe de Servicio',
        'Director Médico',
        'Eminencia Médica',
    ],
    'Enfermería': [
        'Asistente Estudiantil',
        'Practicante de Cuidado',
        'Enfermero/a Junior',
        'Especialista de Sala',
        'Cuidados Intensivos',
        'Jefe/a de Enfermería',
        'Supervisor/a Hospitalario',
        'Gestor/a de Salud',
        'Director/a de Cuidados',
        'Master en Ciencias del Cuidado',
    ],
    'Obstetricia': [
        'Estudiante Obstetra',
        'Practicante Pre-profesional',
        'Obstetra Asistencial',
        'Especialista Materno-Infantil',
        'Asesor/a de Salud Sexual',
        'Jefe/a de Sala de Partos',
        'Supervisor/a Gineco-Obstétrica',
        'Director/a de Salud Reproductiva',
        'Master en Salud Maternal',
        'Eminencia de la Salud Maternal',
    ],
    'Administración de Empresas': [
        'Asistente de Gestión',
        'Analista Junior',
        'Coordinador de Operaciones',
        'Administrador de Proyectos',
        'Jefe de Área',
        'Gerente de Unidad',
        'Director Operativo',
        'Vicepresidente Ejecutivo',
        'Chief Executive Officer (CEO)',
        'Líder Corporativo Internacional',
    ],
    'Contabilidad': [
        'Auxiliar Contable',
        'Asistente Tributario',
        'Contador Junior',
        'Auditor de Operaciones',
        'Contador Senior',
        'Jefe de Finanzas',
        'Controller Financiero',
        'Auditor General',
        'Chief Financial Officer (CFO)',
        'Maestro en Estrategia Financiera',
    ],
    'Ingeniería Civil': [
        'Cadete de Obra',
        'Auxiliar de Campo',
        'Ingeniero Residente Jr.',
        'Diseñador Estructural',
        'Ingeniero Residente Sr.',
        'Inspector de Infraestructura',
        'Gerente de Proyecto',
        'Director de Grandes Obras',
        'Consultor Internacional',
        'Gran Arquitecto del Entorno',
    ],
    'Ingeniería Industrial': [
        'Analista de Procesos Jr.',
        'Asistente de Operaciones',
        'Ingeniero de Calidad',
        'Optimizado de Cadena de Suministro',
        'Jefe de Planta',
        'Gerente de Manufactura',
        'Director de Logística',
        'Vicepresidente de Operaciones',
        'Chief Operating Officer (COO)',
        'Maestro de la Eficiencia Global',
    ],
    'Ingeniería de Minas': [
        'Practicante de Mina',
        'Auxiliar de Geología',
        'Ingeniero de Minado Jr.',
        'Especialista en Geotecnia',
        'Jefe de Turno',
        'Superintendente de Mina',
        'Gerente de Operaciones Mineras',
        'Director de Complejos Mineros',
        'Consultor Minero Global',
        'Comandante de Recursos del Subsuelo',
    ],
    'Arquitectura': [
        'Dibujante Técnico',
        'Proyectista Jr.',
        'Arquitecto Diseñador',
        'Coordinador BIM',
        'Arquitecto Principal',
        'Director de Taller',
        'Gestor Urbano',
        'Maestro de la Forma y Espacio',
        'Arquitecto Visionario',
        'Gran Diseñador de Entornos',
    ],
    'Ingeniería de Sistemas': [
        'Scripting Padawan',
        'Junior Developer',
        'Full Stack Engineer',
        'DevOps Specialist',
        'Senior Software Architect',
        'Tech Lead',
        'VP of Engineering',
        'Chief Technology Officer (CTO)',
        'System Visionary',
        'Grandmaster Cyber Architect',
    ],
    'Derecho': [
        'Practicante Legal',
        'Pasante de Bufete',
        'Abogado Junior',
        'Consultor Jurídico',
        'Abogado Litigante',
        'Socio de Firma',
        'Juez de Jurisdicción',
        'Fiscal Superior',
        'Magistrado',
        'Jurista Supremo de la Ley',
    ],
    'Psicología': [
        'Observador Conductual',
        'Asistente de Evaluación',
        'Psicometrista Jr.',
        'Practicante Clínico',
        'Psicólogo/a Colegiado/a Jr.',
        'Terapeuta Especialista',
        'Consultor/a de Salud Mental',
        'Director/a de Bienestar Psicológico',
        'Master en Ciencias de la Mente',
        'Sabio de la Psique Humana',
    ],
    'Odontología': [
        'Estudiante Preclínico',
        'Asistente Dental',
        'Practicante Odontológico Jr.',
        'Interno de Clínica Dental',
        'Cirujano Dentista Jr.',
        'Especialista en Rehabilitación Oral',
        'Director/a de Clínica Odontológica',
        'Jefe de Cirugía Maxilofacial',
        'Maestro de la Estética Dental',
        'Eminencia Odontológica Global',
    ],
    'Nutrición y Dietética': [
        'Asistente Dietético',
        'Evaluador Nutricional Jr.',
        'Practicante Clínico Nutricional',
        'Nutricionista Comunitario',
        'Nutricionista Clínico Jr.',
        'Especialista en Nutrición Deportiva',
        'Jefe de Servicio Nutricional',
        'Director de Salud Metabólica',
        'Master en Ciencias Nutricionales',
        'Guardián del Bienestar Nutricional',
    ],
    'Farmacia y Bioquímica': [
        'Asistente de Laboratorio',
        'Practicante Farmacéutico',
        'Analista Químico Jr.',
        'Farmacéutico Asistencial',
        'Químico Farmacéutico Jr.',
        'Especialista en Farmacovigilancia',
        'Director Técnico Farmacéutico',
        'Jefe de Desarrollo Farmacéutico',
        'Master en Bioquímica Médica',
        'Alquimista de la Ciencia Farmacéutica',
    ],
    'Economía': [
        'Analista de Datos Económicos Jr.',
        'Asistente de Investigación',
        'Econometrista Jr.',
        'Analista Financiero y de Mercado',
        'Economista Asociado',
        'Consultor Económico Senior',
        'Jefe de Estudios Económicos',
        'Director de Política Fiscal y Monetaria',
        'Chief Economist',
        'Estratega Económico Global',
    ],
    'Marketing y Publicidad': [
        'Trainee de Mercadotecnia',
        'Analista de Social Media & Ads',
        'Especialista en Growth Jr.',
        'Brand Strategist',
        'Campaign Manager',
        'Director de Cuentas Creativas',
        'Head of Growth & Marketing',
        'Chief Marketing Officer (CMO)',
        'Estratega de Mercado Global',
        'Titán de las Marcas y Mercados',
    ],
    'Negocios Internacionales': [
        'Asistente de Comercio Exterior',
        'Analista de Importaciones / Exportaciones',
        'Coordinador de Aduanas y Logística',
        'Especialista en Negociaciones Globales',
        'Gerente de Comercio Exterior',
        'Director de Expansión Global',
        'Consultor de Mercados Internacionales',
        'Vicepresidente de Operaciones Globales',
        'Chief Global Officer (CGO)',
        'Embajador de Comercio Internacional',
    ],
    'Ingeniería Ambiental': [
        'Cadete de Monitoreo Ambiental',
        'Asistente de Calidad y Recursos',
        'Analista de Impacto Ambiental Jr.',
        'Ingeniero de Sostenibilidad',
        'Especialista en Gestión de Ecosistemas',
        'Auditor Ambiental Senior',
        'Jefe de Seguridad y Medio Ambiente (HSE)',
        'Director de Cambio Climático y Sostenibilidad',
        'Consultor Ecológico Internacional',
        'Guardián Supremo de la Biósfera',
    ],
    'Ingeniería Mecánica': [
        'Cadete de Taller Mecánico',
        'Auxiliar de Mantenimiento',
        'Diseñador CAD / CAM Jr.',
        'Ingeniero de Confiabilidad',
        'Ingeniero de Proyectos Mecánicos',
        'Jefe de Mantenimiento y Maquinaria',
        'Gerente de Ingeniería Mecánica',
        'Director de Operaciones Térmicas e Industriales',
        'Consultor Mecatrónico Global',
        'Maestro de las Máquinas y Motores',
    ],
    'Ingeniería Electrónica': [
        'Cadete de Circuitos',
        'Técnico de Integración Electrónica',
        'Desarrollador de Sistemas Embebidos Jr.',
        'Ingeniero de Automatización',
        'Diseñador de Hardware & IoT',
        'Jefe de Telecomunicaciones y Control',
        'Gerente de Automatización Industrial',
        'Director de Robótica e Innovación',
        'Consultor en Microelectrónica Global',
        'Arquitecto Supremo de Señales y Circuitos',
    ],
    'Ingeniería de Software': [
        'Code Explorer Jr.',
        'Software Developer Intern',
        'Full Stack Engineer Jr.',
        'Cloud & Backend Specialist',
        'Senior Software Engineer',
        'Software Architect',
        'Principal Engineer',
        'Director de Ingeniería de Software',
        'VP of Software Systems',
        'Grandmaster Software Visionary',
    ],
    'Ciencia de Datos e Inteligencia Artificial': [
        'Data Scout Jr.',
        'Analista de Datos y BI',
        'Machine Learning Practitioner',
        'Data Scientist Jr.',
        'Senior AI Engineer',
        'Data & AI Architect',
        'Head of Artificial Intelligence',
        'Chief Data & AI Officer (CDAO)',
        'Pionero en Redes Neuronales y AGI',
        'Oráculo Supremo del Dato y la IA',
    ],
    'Ciencias de la Comunicación': [
        'Redactor & Productor Jr.',
        'Asistente de Medios y Prensa',
        'Cronista & Creador de Contenido',
        'Periodista / Comunicador Corporativo',
        'Jefe de Redacción y Medios',
        'Director de Estrategia Digital',
        'Jefe de Prensa y Relaciones Públicas',
        'Director de Comunicaciones (CCO)',
        'Líder de Medios Masivos',
        'Maestro de la Narrativa Global',
    ],
    'Educación': [
        'Practicante de Aula',
        'Asistente Pedagógico',
        'Docente de Nivel Escolar',
        'Especialista en Didáctica e Innovación',
        'Coordinador Pedagógico',
        'Diseñador Curricular',
        'Director Académico',
        'Decano de Facultad Educativa',
        'Ministro / Asesor de Políticas Educativas',
        'Maestro Formador de Generaciones',
    ],
    'Otra carrera': [
        'Estudiante Universitario/a',
        'Aprendiz Dedicado/a',
        'Practicante Pre-Profesional',
        'Especialista Junior',
        'Profesional Competente',
        'Especialista Senior',
        'Líder de Proyecto',
        'Director/a de Especialidad',
        'Maestro/a de su Disciplina',
        'Líder Titán y Referente',
    ],
};

const DEFAULT_RANKS = [
    'Estudiante Inicial',
    'Aprendiz Dedicado',
    'Practicante',
    'Especialista Junior',
    'Profesional',
    'Especialista Senior',
    'Líder de Proyecto',
    'Director de Área',
    'Maestro de Disciplina',
    'Líder Absoluto',
];

/**
 * Obtiene el título profesional según la carrera exacta y la fase (1-10).
 *
 * @param {string|null} career Nombre exacto de la carrera
 * @param {number} phase Número de fase (1 a 10)
 * @returns {string} Título profesional evolutivo
 */
export function getCareerRankTitle(career, phase = 1) {
    const validPhase = Math.min(Math.max(Number(phase) || 1, 1), 10);
    const ranks = CAREER_RANKS[career] || DEFAULT_RANKS;
    return ranks[validPhase - 1] || ranks[0];
}
